# -*- coding: utf-8 -*-
"""RandomForest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AVnBbwYJVaucSzk81Ryjv1gUd_Xl-PZ1
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

digits = load_digits()

df = pd.DataFrame(digits.data)
df['target'] = digits.target

df.head()

features = df.drop(columns = 'target', axis=1)
target = df['target']

X_train, X_test, Y_train, Y_test = train_test_split(features, target, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=20, random_state=2)
model.fit(X_train, Y_train)
model.score(X_train, Y_train)
Y_predict = model.predict(X_test)

cm = confusion_matrix(Y_test, Y_predict)

print(cm)

plt.figure(figsize=(10,7))
sn.heatmap(cm, annot=True, fmt='d')
plt.xlabel('Predicted')
plt.ylabel('Truth')
plt.show()